version: "3.7"

services:

  db:
    image: mysql:5.7
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: php_myadmin_symfony_docker
    restart: always
    depends_on:
      - db 
    ports:
      - 8080:80
    environment: 
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  
  www:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: www_docker_symfony
    ports:
      - "8471:80"
    volumes:
      - type: bind
        source: ./php/vhosts/
        target: /etc/apache2/sites-enabled/ 
      - type: bind
        source: .
        target: /var/www/
    restart: always
    networks:
      - dev




networks:
   dev:


volumes:
  db_data: